name: Build and Deploy to GCP

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{  secrets.GCP_PROJECT_ID  }}
  GCE_INSTANCE: j00per 
  GCE_INSTANCE_ZONE: ${{  secrets.GCP_ZONE  }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
        with:
          version: '290.0.1'
          service_account_key: ${{  secrets.GCP_SA_KEY  }}
          project_id: ${{  secrets.GCP_PROJECT_ID  }}
