name: Deploy to AWS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Check npm version
      run: npm -v

    - name: Install dependencies
      run: npm install
      
    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_USER: "ubuntu"
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_private_key
        chmod 600 ssh_private_key
        scp -o StrictHostKeyChecking=no -i ssh_private_key deploy.zip ${EC2_USER}@${{ secrets.EC2_HOST }}:/home/ubuntu/
        ssh -o StrictHostKeyChecking=no -i ssh_private_key ${EC2_USER}@${{ secrets.EC2_HOST }} << 'EOF'
          unzip -o /home/ubuntu/deploy.zip -d /home/ubuntu/your-app-folder/
          cd /home/ubuntu/your-app-folder/
          npm install --production
          pm2 restart index.js
        EOF
      shell: bash

    - name: Deploy with AWS CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name j00-codedeploy \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name deployuser

    - name: Clean up
      run: rm ssh_private_key
