name: Deploy to GCP

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        ssh-agent bash -c 'ssh-add private_key; ssh-add -l'

    - name: Deploy to GCP
      run: |
        ssh -o StrictHostKeyChecking=no hyunsoo@34.64.186.27 << 'EOF'
        cd /var/www/j00.shop
        git pull origin main
        npm install
        pm2 restart inde.js
        EOF
